defmodule GearflowDemo.Suppliers.Brands do
  @moduledoc """
  A list of.
  """

  def all() do
    [
      {"armadillo", "Armadillo"},
      {"arrow-safety-devices", "Arrow Safety Devices"},
      {"aro-equipments", "ARO Equipments"},
      {"alpine", "Alpine"},
      {"advance-forklift", "Advance Forklift"},
      {"argo", "Argo"},
      {"athey-street-sweeper", "Athey Street Sweeper"},
      {"atp-tools", "ATP Tools"},
      {"advanced-dc-motors", "Advanced Dc Motors"},
      {"advance-lifts", "Advance Lifts"},
      {"ansul", "Ansul"},
      {"armstrong", "Armstrong"},
      {"allianz", "Allianz"},
      {"arrow-material-handling-products", "Arrow Material Handling Products"},
      {"acdelco", "Acdelco"},
      {"airman-usa-corporation-auc", "Airman Usa Corporation (Auc)"},
      {"alumaloft", "Alumaloft"},
      {"alpha-lift", "Alpha Lift"},
      {"atlas-copco", "Atlas Copco"},
      {"algas", "Algas"},
      {"aerial-specialists-inc", "Aerial Specialists Inc"},
      {"anderson", "Anderson"},
      {"aisin", "Aisin"},
      {"atlet", "Atlet"},
      {"ausa", "AUSA"},
      {"autolite", "Autolite"},
      {"airgas", "Airgas"},
      {"allis-chalmers", "Allis Chalmers"},
      {"barrett", "Barrett"},
      {"bca", "BCA"},
      {"bandit-scissor-lifts", "Bandit Scissor Lifts"},
      {"barry", "Barry"},
      {"bendi", "Bendi"},
      {"balkancar", "Balkancar"},
      {"baldor", "Baldor"},
      {"baldwin", "Baldwin"},
      {"bando", "Bando"},
      {"bandit-industries-inc", "Bandit Industries, Inc."},
      {"backtrack", "Backtrack"},
      {"bendix", "Bendix"},
      {"bolzoni", "Bolzoni"},
      {"bobcat", "Bobcat"},
      {"bertea", "Bertea"},
      {"bigtex", "Bigtex"},
      {"beam", "Beam"},
      {"biljax", "Biljax"},
      {"boman", "Boman"},
      {"barber-greene", "Barber-Greene"},
      {"bullard", "Bullard"},
      {"bird-ladder-scaffold-plank", "Bird Ladder Scaffold Plank"},
      {"brush-wolf", "Brush Wolf"},
      {"bt", "BT"},
      {"bishamon", "Bishamon"},
      {"black-and-decker", "Black &amp; Decker"},
      {"braden-winch", "Braden Winch"},
      {"blackstone-mc", "Blackstone MC"},
      {"blastrac", "Blastrac"},
      {"blue-diamond-attachments", "Blue Diamond Attachments"},
      {"blue-giant", "Blue Giant"},
      {"bluebird", "Bluebird"},
      {"bolle", "Bolle"},
      {"brudi", "Brudi"},
      {"bomag", "BOMAG"},
      {"breuer-tornado", "Breuer Tornado"},
      {"bosch", "Bosch"},
      {"big-joe", "Big Joe"},
      {"borg-warner", "Borg Warner"},
      {"bower", "Bower"},
      {"boxer-equipment", "Boxer Equipment"},
      {"brad-harris", "Brad Harris"},
      {"baoli", "Baoli"},
      {"baker", "Baker"},
      {"briggs-and-stratton", "Briggs &amp; Stratton"},
      {"broderson", "Broderson"},
      {"bronto-skylift", "Bronto Skylift"},
      {"benju", "Benju"},
      {"b-e-pressure", "B.E. Pressure"},
      {"bush-hog", "Bush Hog"},
      {"bwise-trailers", "BWISE Trailers"},
      {"best-trailer", "Best Trailer"},
      {"century", "Century"},
      {"cableform", "Cableform"},
      {"canycom", "Canycom"},
      {"clark-golf-carts", "Clark Golf Carts"},
      {"cardinal", "Cardinal"},
      {"cam-attachments", "CAM Attachments"},
      {"case-construction-equipment", "CASE Construction Equipment"},
      {"chicago-pneumatic", "Chicago Pneumatic"},
      {"cc-power-ddc-converters", "CC Power (Ddc Converters)"},
      {"cat-lift-trucks", "Cat Lift Trucks"},
      {"cep", "CEP"},
      {"cushman", "Cushman"},
      {"cart-parts", "Cart-Parts"},
      {"calavar", "Calavar"},
      {"champ-unilift", "Champ Unilift"},
      {"champion", "Champion"},
      {"continental-equipment-company", "Continental Equipment Company"},
      {"china-pallet-truck", "China Pallet Truck"},
      {"chl", "CHL"},
      {"club-car", "Club Car"},
      {"chrysler", "Chrysler"},
      {"clark-material-handling-company", "Clark Material Handling Company"},
      {"clarke-american-sanders", "Clarke American Sanders"},
      {"clarke-sweepers", "Clarke Sweepers"},
      {"carraro", "Carraro"},
      {"cnh-industrial", "CNH Industrial"},
      {"columbia", "Columbia"},
      {"crown", "Crown "},
      {"combilift", "Combilift"},
      {"case-ih-agriculture-and-farm-equipment", "Case IH Agriculture And Farm Equipment"},
      {"combi-packaging-systems", "Combi Packaging Systems"},
      {"concrete-polishing-hq", "Concrete Polishing Hq"},
      {"condor-time-mfg", "Condor / Time Mfg"},
      {"cordova-safety-products", "Cordova Safety Products"},
      {"cotterman", "Cotterman"},
      {"cummins", "Cummins"},
      {"curtis-instrument", "Curtis Instrument"},
      {"carlisle", "Carlisle"},
      {"champ-luber-finer", "Champ / Luber-Finer"},
      {"castex", "Castex"},
      {"cat", "Cat"},
      {"cascade", "Cascade"},
      {"deutsch", "Deutsch"},
      {"dalian", "Dalian"},
      {"durascamp", "Durascamp"},
      {"ditch-witch", "Ditch Witch"},
      {"dri-eaz", "Dri-Eaz"},
      {"delco-remy", "Delco-Remy"},
      {"davis", "Davis"},
      {"daewoo", "Daewoo"},
      {"dynapac", "Dynapac"},
      {"donaldson", "Donaldson"},
      {"donkey-lift", "Donkey Lift"},
      {"dz", "Dz"},
      {"dc-motor-parts", "DC Motor Parts"},
      {"dodge", "Dodge"},
      {"deutz", "Deutz"},
      {"denka-lift", "Denka Lift"},
      {"dynatex", "Dynatex"},
      {"dana", "Dana"},
      {"discover-battery", "Discover Battery"},
      {"demco", "Demco"},
      {"delphi", "Delphi"},
      {"dewalt", "Dewalt"},
      {"del-steel", "Del Steel"},
      {"diamond-products", "Diamond Products"},
      {"dieci", "Dieci"},
      {"dockstocker", "Dockstocker"},
      {"dmi", "DMI"},
      {"dixie-chopper", "Dixie Chopper"},
      {"doosan", "Doosan"},
      {"donkee-lift", "DonKee Lift"},
      {"dupont", "Dupont"},
      {"drexel", "Drexel"},
      {"echo", "ECHO"},
      {"effer-cranes", "Effer Cranes"},
      {"elgin-sweeper", "Elgin Sweeper"},
      {"ecoa", "ECOA"},
      {"ellwood", "Ellwood"},
      {"ep-forklift", "EP Forklift"},
      {"eimco", "EIMCo"},
      {"electric-eel", "Electric Eel"},
      {"esco", "Esco"},
      {"etc-henderson", "Etc Henderson"},
      {"eagleman", "Eagleman"},
      {"eagle-manufacturing-company", "Eagle Manufacturing Company"},
      {"edison", "Edison"},
      {"edco", "EDCO"},
      {"edic", "EDIC"},
      {"ez-rizer", "EZ Rizer"},
      {"essex-silverline", "Essex Silverline"},
      {"ecco", "ECCO"},
      {"eurolifter", "Eurolifter"},
      {"ergodyne", "Ergodyne"},
      {"economy", "Economy"},
      {"eager-beaver-trailers", "Eager Beaver Trailers"},
      {"ecolift", "Ecolift"},
      {"enduro-bearings", "Enduro Bearings"},
      {"e-z-go", "E-Z-Go"},
      {"epw", "EPW"},
      {"erskine-attachments", "Erskine Attachments"},
      {"e-parts", "E-Parts"},
      {"east-penn", "East Penn"},
      {"eaton", "Eaton"},
      {"elliot-hi-reach", "Elliot Hi-Reach"},
      {"elwell-parker", "Elwell-Parker"},
      {"etiflex", "Etiflex"},
      {"exmile-tyres", "Exmile Tyres"},
      {"fontaine-commercial-trailer", "Fontaine Commercial Trailer"},
      {"federal-signal", "Federal Signal"},
      {"fabtech", "Fabtech"},
      {"fairchild-international", "Fairchild International"},
      {"fag", "FAG"},
      {"factory-cat", "Factory Cat"},
      {"fleetguard", "Fleetguard"},
      {"feeler", "Feeler"},
      {"factor", "Factor"},
      {"fasse-cranes", "Fasse Cranes"},
      {"florida-pneumatic", "Florida Pneumatic"},
      {"fahel", "Fahel"},
      {"flight-systems", "Flight Systems"},
      {"fmc", "FMC"},
      {"flow-ezy", "Flow Ezy"},
      {"fairfield-torque-hub", "Fairfield Torque Hub"},
      {"fiatt-allis", "Fiatt-Allis"},
      {"freightliner", "Freightliner"},
      {"flopac", "Flopac"},
      {"fabtek", "Fabtek"},
      {"fenwick", "Fenwick"},
      {"fram", "FRAM"},
      {"ferraz", "Ferraz"},
      {"fiat", "Fiat"},
      {"finn", "Finn"},
      {"ford", "Ford"},
      {"general-electric", "General Electric"},
      {"greenlee", "Greenlee"},
      {"grip", "Grip"},
      {"genie", "Genie"},
      {"gmc", "GMC"},
      {"generac", "Generac"},
      {"gorman-rupp", "Gorman-Rupp"},
      {"galion", "Galion"},
      {"gehl", "Gehl"},
      {"grammer", "Grammer"},
      {"gojo", "GOJO"},
      {"garretson", "Garretson"},
      {"gsi-scissor-lifts", "GSI Scissor Lifts"},
      {"gray-forklift-jack", "Gray Forklift Jack"},
      {"grove", "Grove"},
      {"gardner-denver", "Gardner Denver"},
      {"general-motors", "General Motors"},
      {"general-equipment", "General Equipment"},
      {"g-power", "G Power"},
      {"gregory", "Gregory"},
      {"gates", "Gates"},
      {"generic-parts", "Generic Parts"},
      {"gradall", "Gradall"},
      {"gottwald-crane", "Gottwald Crane"},
      {"grandwatt-power-solutions", "Grandwatt Power Solutions"},
      {"gleason-reel", "Gleason Reel"},
      {"goodyear", "Goodyear"},
      {"heavy-duty-starters", "Heavy Duty Starters"},
      {"hoof", "Hoof"},
      {"haviland", "Haviland"},
      {"hubtex", "Hubtex"},
      {"hand-pallet", "Hand Pallet"},
      {"hyster", "Hyster"},
      {"haulotte", "Haulotte"},
      {"hunter-lift", "Hunter Lift"},
      {"hy-brid-lifts", "Hy-Brid Lifts"},
      {"hydrac", "Hydrac"},
      {"hydroelectric-lift-truck", "Hydroelectric Lift Truck"},
      {"hangcha", "Hangcha"},
      {"hamm", "Hamm"},
      {"hexarmor", "Hexarmor"},
      {"hyundai", "Hyundai"},
      {"hytsu", "Hytsu"},
      {"haldex-barnes", "Haldex-Barnes"},
      {"hydro-ax", "Hydro-Ax"},
      {"husqvarna", "Husqvarna"},
      {"hitachi-equipment", "Hitachi Equipment"},
      {"h-o-bostrom", "H.O. Bostrom"},
      {"hawker", "Hawker"},
      {"haulmark", "Haulmark"},
      {"haldex", "Haldex"},
      {"hoover", "Hoover"},
      {"honda-equipment", "Honda Equipment"},
      {"hamech", "Hamech"},
      {"heritage-truck-equipment", "Heritage Truck Equipment"},
      {"husco", "Husco"},
      {"hoist-liftruck", "Hoist Liftruck"},
      {"hendley", "Hendley"},
      {"hoyt-electric", "Hoyt Electric"},
      {"heli", "Heli"},
      {"halla", "Halla"},
      {"hammer-s-r-l", "Hammer S.R.L."},
      {"hercules", "Hercules"},
      {"hilti", "Hilti"},
      {"hi-ranger", "Hi Ranger"},
      {"howard-leight", "Howard Leight"},
      {"hull-lift", "Hull Lift"},
      {"isuzu-motors-ltd", "Isuzu Motors Ltd."},
      {"iko", "IKO"},
      {"indy-the-power-buggy", "Indy - The Power Buggy"},
      {"integrity-trailers", "Integrity Trailers"},
      {"ihimer", "IHIMER"},
      {"international-rectifier", "International Rectifier"},
      {"igus", "Igus"},
      {"ihi", "IHI"},
      {"intertractor-america", "Intertractor America"},
      {"ingersoll-rand", "Ingersoll Rand"},
      {"ina", "INA"},
      {"international-harvester", "International Harvester"},
      {"interthor", "Interthor"},
      {"interstate-batteries", "Interstate Batteries"},
      {"international-paystar", "International Paystar"},
      {"iskra", "Iskra"},
      {"impco", "IMPCO"},
      {"jungheinrich", "Jungheinrich"},
      {"jlg", "JLG"},
      {"jcb", "JCB"},
      {"jands-carburetion", "J&amp;S Carburetion"},
      {"jacobson", "Jacobson"},
      {"johnston-sweepers", "Johnston Sweepers"},
      {"j-i-case", "J.I. Case"},
      {"jackson-safety", "Jackson Safety"},
      {"jamco", "Jamco"},
      {"jet-tools", "Jet Tools"},
      {"john-deere", "John Deere"},
      {"joy-manufacturing", "Joy Manufacturing"},
      {"kohler", "Kohler"},
      {"kayaba", "Kayaba"},
      {"k-and-j", "K And J"},
      {"kobelco", "Kobelco"},
      {"karrior", "Karrior"},
      {"kalmar", "Kalmar"},
      {"komatsu", "Komatsu"},
      {"konecranes", "Konecranes"},
      {"koyo", "Koyo"},
      {"kubota", "Kubota"},
      {"kw-tools", "KW Tools"},
      {"kyodo-america", "Kyodo America"},
      {"koehring", "Koehring"},
      {"karcher", "Karcher"},
      {"kalamazoo", "Kalamazoo"},
      {"kawasaki", "Kawasaki"},
      {"kenhar-forks", "Kenhar Forks"},
      {"kent", "Kent"},
      {"kato-imer", "Kato Imer"},
      {"lift-rite", "Lift Rite"},
      {"lansing-bagnall", "Lansing Bagnall"},
      {"lx", "LX"},
      {"lucas", "Lucas"},
      {"linkit", "Linkit"},
      {"lift-a-loft", "Lift-A-Loft"},
      {"landini", "Landini"},
      {"lights", "Lights"},
      {"l-b-white", "L.B. White"},
      {"linde", "Linde"},
      {"liugong", "Liugong"},
      {"lafis", "Lafis"},
      {"lull", "Lull"},
      {"lancer-boss", "Lancer Boss"},
      {"lister-petter-engines", "Lister Petter Engines"},
      {"little-beaver", "Little Beaver"},
      {"land-pride", "Land Pride"},
      {"laymor", "LayMor"},
      {"legend", "Legend"},
      {"link-belt", "Link-Belt"},
      {"lenz-hydraulics", "Lenz Hydraulics"},
      {"lansing", "Lansing"},
      {"liebherr", "Liebherr"},
      {"lowe-attachments", "Lowe Attachments"},
      {"long-airdox", "Long Airdox"},
      {"lonking", "Lonking"},
      {"ledwell", "Ledwell"},
      {"mandh", "M&amp;H"},
      {"mariotti", "Mariotti"},
      {"mustang", "Mustang"},
      {"mac-tools", "Mac Tools"},
      {"manitowoc", "Manitowoc"},
      {"master-craft", "Master Craft"},
      {"marco-tiger", "Marco Tiger"},
      {"mile-max", "Mile Max"},
      {"malish", "Malish"},
      {"multiquip", "Multiquip"},
      {"mann-filters", "Mann Filters"},
      {"msa", "Msa"},
      {"multiton", "Multiton"},
      {"mico", "MICO"},
      {"motrec-pbc", "Motrec Pbc"},
      {"mark-and-parker-lifts", "Mark &amp; Parker Lifts"},
      {"mccloskey", "Mccloskey"},
      {"marklift", "Marklift"},
      {"minuteman-sweeper", "Minuteman Sweeper"},
      {"marvel", "Marvel"},
      {"millerwelds", "MillerWelds"},
      {"multilift", "Multilift"},
      {"massey-ferguson", "Massey Ferguson"},
      {"master-power", "Master Power"},
      {"miller-curber", "Miller Curber"},
      {"mp", "Mp"},
      {"milwaukee-tool", "Milwaukee Tool"},
      {"maxi", "Maxi"},
      {"mercury-pettibone", "Mercury-Pettibone"},
      {"mckissick-blocks", "McKissick Blocks"},
      {"maximal", "Maximal"},
      {"magni", "Magni"},
      {"mbw", "Mbw"},
      {"mccormick", "McCormick"},
      {"mec", "MEC"},
      {"motorcraft", "Motorcraft"},
      {"melex", "Melex"},
      {"merlo", "Merlo"},
      {"magnum", "Magnum"},
      {"metal-tech", "Metal Tech"},
      {"mi-t-m-corp", "Mi-T-M Corp."},
      {"michigan-pneumatic-tool", "Michigan Pneumatic Tool"},
      {"micro-switch", "Micro Switch"},
      {"mk-diamond-products", "Mk Diamond Products"},
      {"machine-electric", "Machine Electric"},
      {"milwaukee-rubber-products", "Milwaukee Rubber Products"},
      {"mazda", "Mazda"},
      {"mite-e-lift", "Mite-E-Lift"},
      {"magneti-marelli", "Magneti Marelli"},
      {"modex", "Modex"},
      {"manitou", "Manitou"},
      {"multi-clean", "Multi-Clean"},
      {"moldex", "Moldex"},
      {"moffett-truck", "Moffett Truck"},
      {"mack-trucks", "Mack Trucks"},
      {"mobile", "Mobile"},
      {"mitsubishi", "Mitsubishi"},
      {"ml-kishigo", "Ml Kishigo"},
      {"new-holland", "New Holland"},
      {"npk", "NPK"},
      {"north-safety", "North Safety"},
      {"nexen", "Nexen"},
      {"ntn", "NTN"},
      {"nivel", "Nivel"},
      {"namco", "Namco"},
      {"napa", "NAPA"},
      {"nobles", "Nobles"},
      {"nu-star-inc", "Nu-Star Inc."},
      {"national-super-service", "National Super Service"},
      {"ngk", "NGK"},
      {"niftylift", "Niftylift"},
      {"nikko", "Nikko"},
      {"nippondenso", "Nippondenso"},
      {"nissan-forklifts", "Nissan Forklifts"},
      {"no-ramp-trailers", "No Ramp Trailers"},
      {"no-waste-tape", "No Waste Tape"},
      {"noblelift", "Noblelift"},
      {"nordskog", "Nordskog"},
      {"noland", "Noland"},
      {"norton-abrasives", "Norton Abrasives"},
      {"nova", "Nova"},
      {"novax", "Novax"},
      {"nsk", "NSK"},
      {"nyk", "NYK"},
      {"olympian", "Olympian"},
      {"onan", "Onan"},
      {"orec-america", "Orec America"},
      {"oem-controls", "OEM Controls"},
      {"omega", "Omega"},
      {"ottawa-yard-mule", "Ottawa Yard Mule"},
      {"optibelt", "Optibelt"},
      {"parker-hose-fitting", "Parker Hose/Fitting"},
      {"pertronix", "Pertronix"},
      {"perkins", "Perkins"},
      {"prentice", "Prentice"},
      {"pettibone", "Pettibone"},
      {"pileco", "Pileco"},
      {"purolator", "Purolator"},
      {"pandh-cranes", "P&amp;H Cranes"},
      {"pengo", "Pengo"},
      {"preco", "Preco"},
      {"palazzani", "Palazzani"},
      {"penray", "Penray"},
      {"peugeot", "Peugeot"},
      {"primatech", "Primatech"},
      {"powr-flite", "Powr-Flite"},
      {"paladin-attachments", "Paladin Attachments"},
      {"pargo", "Pargo"},
      {"power-boss", "Power Boss"},
      {"prestolite", "Prestolite"},
      {"paslode", "Paslode"},
      {"pullman-holt", "Pullman Holt"},
      {"palfinger", "Palfinger"},
      {"pramac", "Pramac"},
      {"pb-lift", "PB Lift"},
      {"premier-pallet-truck", "Premier Pallet Truck"},
      {"powermatic", "Powermatic"},
      {"pallet-mule", "Pallet Mule"},
      {"peterbilt", "Peterbilt"},
      {"phoenix-scissor-lifts", "Phoenix Scissor Lifts"},
      {"promark", "Promark"},
      {"pioneer-eclipse", "Pioneer Eclipse"},
      {"pq-controls", "PQ Controls"},
      {"princeton", "Princeton"},
      {"paletrans", "Paletrans"},
      {"pacific-floor-care", "Pacific Floor Care"},
      {"prime-mover", "Prime Mover"},
      {"quick-cable", "Quick Cable"},
      {"rice-hydro", "Rice Hydro"},
      {"rockford-scissors", "Rockford Scissors"},
      {"radians", "Radians"},
      {"rocol", "ROCOL"},
      {"roto-zoom", "Roto-Zoom"},
      {"rig-ready", "Rig Ready"},
      {"reynolds", "Reynolds"},
      {"ryan-turf", "Ryan Turf"},
      {"reliance-fall-protection", "Reliance Fall Protection"},
      {"rol-lift", "Rol-Lift"},
      {"ryobi", "Ryobi"},
      {"raymond", "Raymond"},
      {"rightline", "Rightline"},
      {"rosco", "Rosco"},
      {"rebuilt", "Rebuilt"},
      {"rego", "Rego"},
      {"renault", "Renault"},
      {"roadtec", "Roadtec"},
      {"rexroth-a-bosch-company", "Rexroth - A Bosch Company"},
      {"reach-all", "Reach All"},
      {"rhino-alamo-group", "Rhino-Alamo Group"},
      {"rockwell", "Rockwell"},
      {"ramsplitter", "Ramsplitter"},
      {"rema", "Rema"},
      {"sakai", "Sakai"},
      {"soff-cut", "Soff-Cut"},
      {"starlift-equipment", "Starlift Equipment"},
      {"sdlg", "SDLG"},
      {"synchro-start", "Synchro-Start"},
      {"sky-worher", "Sky Worher"},
      {"sauer-danfoss", "Sauer Danfoss"},
      {"sellstrom", "Sellstrom"},
      {"sherpa", "Sherpa"},
      {"super-sight", "Super Sight"},
      {"samuk", "Samuk"},
      {"skf", "SKF"},
      {"square-shooter", "Square Shooter"},
      {"stearns", "Stearns"},
      {"square-d", "Square D"},
      {"solid-deal-tires", "Solid Deal Tires"},
      {"single-pole-connectors", "Single Pole Connectors"},
      {"star", "Star"},
      {"separ", "Separ"},
      {"sumake", "Sumake"},
      {"star-industries", "Star Industries"},
      {"superline", "Superline"},
      {"saltdogg", "Saltdogg"},
      {"systems", "Systems"},
      {"snyflex-hose", "Snyflex Hose"},
      {"skyjack", "SkyJack"},
      {"strato-lift", "Strato-Lift"},
      {"smv", "SMV"},
      {"skil", "Skil"},
      {"snorkel", "Snorkel"},
      {"shark", "Shark"},
      {"stam", "Stam"},
      {"scaffold-plank", "Scaffold Plank"},
      {"seahorse", "Seahorse"},
      {"smith", "Smith"},
      {"schreck", "Schreck"},
      {"simpson", "Simpson"},
      {"safe-t-alert", "Safe-T-Alert"},
      {"star-hydrodyne", "Star-Hydrodyne"},
      {"sioux-tools", "Sioux Tools"},
      {"superior-broom", "Superior Broom"},
      {"sve", "Sve"},
      {"shangli", "Shangli"},
      {"samsung", "Samsung"},
      {"sky-climber", "Sky Climber"},
      {"sany", "Sany"},
      {"skywitch", "SkyWitch"},
      {"stihl", "Stihl"},
      {"sullair", "Sullair"},
      {"sisu", "Sisu"},
      {"scat-trak", "Scat Trak"},
      {"solidboss-tires", "Solidboss Tires"},
      {"sidney-attachments", "Sidney Attachments"},
      {"sumitomo", "Sumitomo"},
      {"sullivan-palatek", "Sullivan Palatek"},
      {"steinbock", "Steinbock"},
      {"still", "Still"},
      {"stone", "Stone"},
      {"simon-aerials", "Simon Aerials"},
      {"sellick", "Sellick"},
      {"superior-tires-and-wheels", "Superior Tires &amp; Wheels"},
      {"skytrak", "SkyTrak"},
      {"sevcon", "Sevcon"},
      {"skyclimber", "Skyclimber"},
      {"trackmobile", "Trackmobile"},
      {"tcm", "TCM"},
      {"totalsource-activewear", "Totalsource Activewear"},
      {"torrington", "Torrington"},
      {"thermoid", "Thermoid"},
      {"telemechanique", "Telemechanique"},
      {"terex", "Terex"},
      {"toro", "Toro"},
      {"texas-pneumatic", "Texas Pneumatic"},
      {"tennant", "Tennant"},
      {"tiresocks", "Tiresocks"},
      {"thor", "Thor"},
      {"tadano", "Tadano"},
      {"tillman", "Tillman"},
      {"tape-switch", "Tape Switch"},
      {"terracycle-regulated-waste", "Terracycle Regulated Waste"},
      {"tug", "Tug"},
      {"toku", "Toku"},
      {"timberjack", "Timberjack"},
      {"teledyne-princeton", "Teledyne Princeton"},
      {"target", "Target"},
      {"tailift", "Tailift"},
      {"tsurumi-pump", "Tsurumi Pump"},
      {"tutus", "Tutus"},
      {"taylor-dunn", "Taylor Dunn"},
      {"tesmec", "Tesmec"},
      {"terminal-supply", "Terminal Supply"},
      {"t-rex-hammer", "T-Rex Hammer"},
      {"teupen", "Teupen"},
      {"trw", "Trw"},
      {"trail-king-industries", "Trail King Industries"},
      {"telsmith", "Telsmith"},
      {"timken", "Timken"},
      {"terraquip", "Terraquip"},
      {"thombert-tires-and-wheels", "Thombert Tires And Wheels"},
      {"tipcon", "Tipcon"},
      {"tomar", "Tomar"},
      {"topperlift", "Topperlift"},
      {"toyota-forklifts", "Toyota Forklifts"},
      {"tecumseh", "Tecumseh"},
      {"takeuchi", "Takeuchi"},
      {"talbert", "Talbert"},
      {"tvh-group", "TVH Group"},
      {"taylor", "Taylor"},
      {"tally-ho", "Tally-Ho"},
      {"truck-lite", "Truck-Lite"},
      {"up-equip", "UP Equip"},
      {"united-contacts", "United Contacts"},
      {"ukey", "Ukey"},
      {"united-tractor", "United Tractor"},
      {"universal-heaters", "Universal Heaters"},
      {"unipoint", "Unipoint"},
      {"united-shoe-machinery", "United Shoe Machinery"},
      {"upright", "UpRight"},
      {"us-electricar", "US Electricar"},
      {"usa-tools", "USA Tools"},
      {"uniroyal-belts", "Uniroyal (Belts)"},
      {"ultra-pallet-jacks-and-sweepers", "Ultra Pallet Jacks &amp; Sweepers"},
      {"unicarriers", "Unicarriers"},
      {"value-jack", "Value Jack"},
      {"victor-reinz", "Victor Reinz"},
      {"vactor", "Vactor"},
      {"vision-air", "Vision Air"},
      {"vulcan-tools", "Vulcan Tools"},
      {"valeo", "Valeo"},
      {"vermeer", "Vermeer"},
      {"volkswagen", "Volkswagen"},
      {"volvo", "Volvo"},
      {"vickers", "Vickers"},
      {"versalift", "Versalift"},
      {"vacall", "Vacall"},
      {"val6", "Val6"},
      {"victor", "Victor"},
      {"wacker-neuson", "Wacker Neuson"},
      {"windsor", "Windsor"},
      {"webster-hydraulic-pumps", "Webster Hydraulic Pumps"},
      {"white-rodgers", "White Rodgers"},
      {"wabco", "Wabco"},
      {"wrangler", "Wrangler"},
      {"wirtgen-group", "Wirtgen Group"},
      {"world-lift", "World-Lift"},
      {"western-star-trucks", "Western Star Trucks"},
      {"weatherhead", "Weatherhead"},
      {"wilson-barrett", "Wilson Barrett"},
      {"weber-products", "Weber Products"},
      {"waukesha", "Waukesha"},
      {"wanco", "Wanco"},
      {"wilson", "Wilson"},
      {"wagner", "Wagner"},
      {"wire-works", "Wire Works"},
      {"white-mobilift", "White Mobilift"},
      {"westchester", "Westchester"},
      {"wisconsin-engine", "Wisconsin Engine"},
      {"wix-air-refiner", "Wix / Air Refiner"},
      {"wolf-lift", "Wolf Lift"},
      {"wrst", "Wrst"},
      {"xinchai", "Xinchai"},
      {"xtreme", "Xtreme"},
      {"yard-marvel", "Yard Marvel"},
      {"yale", "Yale"},
      {"york", "York"},
      {"yamaha", "Yamaha"},
      {"yanmar", "YANMAR"},
      {"yang", "Yang"},
      {"zefer-aerial-lift", "Zefer Aerial Lift"},
      {"zoomlion", "Zoomlion"},
      {"zexel", "Zexel"},
      {"zenith", "Zenith"},
      {"zf-transmission-parts", "ZF Transmission Parts"}
    ]
  end
end
